var num1 = prompt("enter first number");
var num2 = prompt("enter second number");
var sum, sub, multification, division;
var num1 = parseInt(num1);
var num2 = parseInt(num2);
sum = num1 + num2;
sub = num1 - num2;
multification = num1 * num2;
division = num1 / num2;
document.write("sum = " + sum + "<br/>");
document.write("sub =" + sub + "<br/>");
document.write("multification =" + multification + "<br/>" + "division = " + division);